version: '2.1'

services:
  node-express-jenkins:
    image: node-express-jenkins
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js